name 'fission-vagrant'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures fission-vagrant'
long_description 'Installs/Configures fission-vagrant'
version '0.1.0'

depends 'ruby_build'
depends 'postgresql'
depends 'database'
depends 'vagabond'
